### PR TITLE
Add PannerNode

### PR DESCRIPTION
**Pull request by fand**
:hear_no_evil: 

implemented `PannerNode`!
Many codes are from [chromium's Web Audio API implementation](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/modules/webaudio/PannerNode.cpp).

I'm sorry for +1600 diff... I didn't know PannerNode is such a complicated node.

# Files

This P-R includes these files:

```
lib
├── AudioListener.js : AudioListener interface 
├── FloatPoint3D.js : 3D vector class for position, orientation, etc.
├── InvalidStateError.js: an error class required in the spec
├── NotSupportedError.js: an error class required in the spec
├── PannerNode
│   ├── ConeEffect.js : computes gain for sound cone
│   ├── DistanceEffect.js : computes gain for distance effect
│   ├── EqualPowerPanner.js : computes "equalpower" panning algorithm
│   ├── Panner.js : the Parent class for EqualPowerPanner, HRTFPanner (not implemented)
│   ├── PannerNode.js : main AudioNode file
│   ├── PannerProvider.js : a factory for Panner classes
│   └── index.js
└── mathUtils.js
```

Also there are test files for these new modules.

You can try it with `speaker` like this:
`node test/manual-testing/PannerNode-sound-output.js`

# Omitted features
I didn't implement HRTFPanner because it's so complicated.
There's no test for `setVelocity` because it will be deprecated soon.

Some other modules are deprecated in the spec, but I implemented them to make it work.

# License issue
I think it doesn't matter that I translated codes from chromium (which are licensed under BSD and GPLv2).
If it came a problem I'll find another way... :cow2:

### CODE REVIEW

**Comment by sebpiq** [comment]
Hey! Thanks for all the great pull requests!!! This one is still work in progress I guess. Tests would be nice too.

**Comment by fand** [comment]
Chromium PannerNode implementation 
https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/modules/webaudio/PannerNode.cpp

**Comment by fand** [comment]
:muscle:

**Comment by fand** [comment]
rebased & `push -f` ed

**Comment by fand** [comment]
:woot:
https://github.com/WebAudio/web-audio-api/issues/730#issuecomment-188413659

**Comment by hughrawlinson** [comment]
Woohoo! :smile:

**Comment by fand** [comment]
Now it's ready for review!
Updated P-R description.

**Comment by sebpiq** [comment]
Hi @fand ! Sorry for the slow response time, I've been super busy last week, and I will be again this week. I should be able to have a look at this the week of the 14th March. Thanks again for all the work you've done :+1: :+1: :+1:

**Comment by fand** [comment]
ok, thx!

**Comment by sebpiq** [comment]
well done! That's an awesome pull request! Amazing work you did :) I merged it. I think the whole library needs a bit of reorganization (mostly shuffling files around), cause atm it's a bit messy, but that's not your problem ...

**Pull request merged**
